FROM node:17-alpine as build
RUN npm config set registry https://registry.npm.taobao.org/
RUN npm install -g lerna 
WORKDIR /app
COPY package.json .
COPY lerna.json  .
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
RUN lerna bootstrap
RUN npm rebuild esbuild 
CMD ["yarn", "build"]

FROM nginx
COPY --from=build /app/dist /usr/share/nginx/html

